package com.ledgerlens.categorization
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.datetime.Clock
import kotlin.time.Duration
import kotlin.time.Duration.Companion.hours
class FeedbackLoop(private val correctionProcessor: CorrectionProcessor, private val batchRetrainer: BatchRetrainer, private val ruleManager: RuleManager? = null, private val config: FeedbackLoopConfig = FeedbackLoopConfig(), private val clock: Clock = Clock.System) {
    private val mutex = Mutex(); private var totalCorrectionsProcessed: Long = 0; private var lastAnalysisTime = clock.now()
    suspend fun submitCorrection(transactionId: String, features: TransactionFeatures, oldCategoryId: String, newCategoryId: String, originalConfidence: Float, classifierUsed: String): FeedbackResult = mutex.withLock { val result = correctionProcessor.processCorrection(transactionId, features, oldCategoryId, newCategoryId, originalConfidence, classifierUsed); totalCorrectionsProcessed++; batchRetrainer.recordCorrection(); val retrain = if (config.enableAutoRetrain && batchRetrainer.shouldRetrain().shouldRetrain) batchRetrainer.retrain() else null; val ruleAction = result.suggestedRule?.let { if (ruleManager != null && config.enableAutoRuleCreation && it.confidence >= config.autoRuleConfidenceThreshold) ruleManager.createRuleFromSuggestion(it)?.let { r -> RuleAction.Created(r, it) } ?: RuleAction.Suggested(it) else RuleAction.Suggested(it) }; val analysis = if ((clock.now() - lastAnalysisTime) >= config.analysisInterval) { lastAnalysisTime = clock.now(); correctionProcessor.analyzeCorrections() } else null; FeedbackResult(result, retrain, ruleAction, analysis) }
    suspend fun submitBatch(corrections: List<PendingCorrection>): BatchFeedbackResult = mutex.withLock { val result = correctionProcessor.processBatch(corrections); totalCorrectionsProcessed += result.successCount; repeat(result.successCount) { batchRetrainer.recordCorrection() }; val retrain = if (config.enableAutoRetrain && batchRetrainer.shouldRetrain().shouldRetrain) batchRetrainer.retrain() else null; val analysis = correctionProcessor.analyzeCorrections(); BatchFeedbackResult(result, retrain, analysis, analysis.suggestedRules) }
    suspend fun triggerRetrain(): RetrainResult = mutex.withLock { batchRetrainer.retrain() }
    suspend fun getAnalysis(): CorrectionAnalysis = mutex.withLock { correctionProcessor.analyzeCorrections() }
    suspend fun getStats(): FeedbackLoopStats = mutex.withLock { val decision = batchRetrainer.shouldRetrain(); FeedbackLoopStats(totalCorrectionsProcessed, decision.shouldRetrain, when (decision) { is RetrainDecision.NotNeeded -> null; is RetrainDecision.TimeThresholdExceeded -> "Time threshold exceeded"; is RetrainDecision.CorrectionThresholdExceeded -> "Correction count threshold exceeded"; is RetrainDecision.HighRecentCorrectionRate -> "High recent correction rate" }) }
}
data class FeedbackLoopConfig(val enableAutoRetrain: Boolean = true, val enableAutoRuleCreation: Boolean = false, val autoRuleConfidenceThreshold: Float = 0.9f, val autoRuleMinSupport: Int = 5, val analysisInterval: Duration = 1.hours)
data class FeedbackResult(val correctionResult: CorrectionResult, val retrainResult: RetrainResult?, val ruleAction: RuleAction?, val analysis: CorrectionAnalysis?)
data class BatchFeedbackResult(val batchResult: BatchCorrectionResult, val retrainResult: RetrainResult?, val analysis: CorrectionAnalysis, val suggestedRules: List<SuggestedRule>)
data class FeedbackLoopStats(val totalCorrectionsProcessed: Long, val pendingRetrain: Boolean, val retrainReason: String?)
sealed class RuleAction { data class Suggested(val rule: SuggestedRule) : RuleAction(); data class Created(val rule: ClassificationRule, val fromSuggestion: SuggestedRule) : RuleAction() }
interface RuleManager { fun createRuleFromSuggestion(suggestion: SuggestedRule): ClassificationRule?; fun getUserRules(): List<ClassificationRule>; fun setRuleEnabled(ruleId: String, enabled: Boolean); fun deleteRule(ruleId: String): Boolean }
interface ClassificationRule { val id: String; val categoryId: String; val confidence: Float; val priority: Int; val enabled: Boolean; val name: String get() = id; fun matches(features: TransactionFeatures): Boolean }
data class MerchantContainsRule(override val id: String, override val categoryId: String, val patterns: List<String>, override val confidence: Float = 0.9f, override val priority: Int = 100, override val enabled: Boolean = true) : ClassificationRule { override fun matches(features: TransactionFeatures) = patterns.any { features.merchantNormalized.lowercase().contains(it.lowercase()) } }
class DefaultRuleManager : RuleManager { private val userRules = mutableMapOf<String, ClassificationRule>(); private var ruleCounter = 0; override fun createRuleFromSuggestion(suggestion: SuggestedRule): ClassificationRule { val id = "user_rule_${++ruleCounter}"; val rule = MerchantContainsRule(id, suggestion.suggestedCategoryId, listOf(suggestion.merchantPattern.lowercase()), suggestion.confidence.coerceAtMost(0.95f), 95, true); userRules[id] = rule; return rule }; override fun getUserRules() = userRules.values.toList(); override fun setRuleEnabled(ruleId: String, enabled: Boolean) { val r = userRules[ruleId] as? MerchantContainsRule ?: return; userRules[ruleId] = r.copy(enabled = enabled) }; override fun deleteRule(ruleId: String) = userRules.remove(ruleId) != null }
object FeedbackLoopFactory { fun create(classifier: NaiveBayesClassifier = NaiveBayesClassifier(), correctionRepository: CorrectionRepository = InMemoryCorrectionRepository(), statsRepository: PredictionStatsRepository = InMemoryPredictionStatsRepository(), ruleManager: RuleManager? = DefaultRuleManager(), config: FeedbackLoopConfig = FeedbackLoopConfig()): FeedbackLoop { val learner = IncrementalLearner(classifier); val processor = CorrectionProcessor(correctionRepository, statsRepository, learner); val retrainer = BatchRetrainer(correctionRepository, classifier); return FeedbackLoop(processor, retrainer, ruleManager, config) } }
