package com.ledgerlens.categorization
import kotlin.math.ln
import kotlin.math.exp
class NaiveBayesClassifier(private var model: NaiveBayesModel = NaiveBayesModel()) {
    val name: String = "naive-bayes"
    fun classify(features: TransactionFeatures): ClassificationResult { if (model.isEmpty()) return ClassificationResult.unknown(); val scores = mutableMapOf<String, Double>(); for (cat in model.categories) { var lp = ln(model.getCategoryPrior(cat)); model.merchantPriors[features.merchantNormalized]?.get(cat)?.let { lp += ln(it.toDouble()) * 2.0 }; for (t in features.descriptionTokens) lp += ln(model.getTokenProbability(t, cat)); scores[cat] = lp }; if (scores.isEmpty()) return ClassificationResult.unknown(); val sorted = scores.entries.sortedByDescending { it.value }; val top = sorted.first(); val maxLog = scores.values.maxOrNull() ?: 0.0; val expS = scores.mapValues { exp(it.value - maxLog) }; val sum = expS.values.sum(); val norm = expS.mapValues { (it.value / sum).toFloat() }; val conf = norm[top.key] ?: 0f; val alts = sorted.drop(1).take(3).map { CategoryScore(it.key, norm[it.key] ?: 0f) }; val matched = features.descriptionTokens.filter { model.tokenCategoryFrequencies[it]?.containsKey(top.key) == true }; return ClassificationResult(top.key, conf, alts, ClassificationExplanation(name, "Probabilistic classification", merchantPrior = model.merchantPriors[features.merchantNormalized]?.get(top.key), tokenMatches = matched.take(5))) }
    fun train(features: TransactionFeatures, categoryId: String) { model = model.addExample(features, categoryId) }
    fun getModel() = model
    fun loadModel(newModel: NaiveBayesModel) { model = newModel }
}
data class NaiveBayesModel(val categories: Set<String> = emptySet(), val categoryCounts: Map<String, Int> = emptyMap(), val totalExamples: Int = 0, val tokenCategoryFrequencies: Map<String, Map<String, Int>> = emptyMap(), val categoryTokenCounts: Map<String, Int> = emptyMap(), val vocabularySize: Int = 0, val merchantPriors: Map<String, Map<String, Float>> = emptyMap(), val amountBucketCounts: Map<AmountBucket, Map<String, Int>> = emptyMap()) {
    fun isEmpty() = totalExamples == 0
    fun getCategoryPrior(cat: String) = ((categoryCounts[cat] ?: 0) + 1.0) / (totalExamples + categories.size)
    fun getTokenProbability(token: String, cat: String): Double { val f = tokenCategoryFrequencies[token]?.get(cat) ?: 0; val c = categoryTokenCounts[cat] ?: 0; return (f + 0.1) / (c + vocabularySize * 0.1) }
    fun addExample(features: TransactionFeatures, categoryId: String): NaiveBayesModel { val newCats = categories + categoryId; val newCounts = categoryCounts.toMutableMap(); newCounts[categoryId] = (newCounts[categoryId] ?: 0) + 1; val newTokenFreqs = tokenCategoryFrequencies.toMutableMap(); val newCatTokenCounts = categoryTokenCounts.toMutableMap(); newCatTokenCounts[categoryId] = (newCatTokenCounts[categoryId] ?: 0) + features.descriptionTokens.size; var newVocab = vocabularySize; for (t in features.descriptionTokens) { val tm = newTokenFreqs.getOrPut(t) { mutableMapOf() }.toMutableMap(); if (t !in tokenCategoryFrequencies) newVocab++; tm[categoryId] = (tm[categoryId] ?: 0) + 1; newTokenFreqs[t] = tm }; val newMerchantPriors = merchantPriors.toMutableMap(); val mm = newMerchantPriors.getOrPut(features.merchantNormalized) { mutableMapOf() }.toMutableMap(); val cc = mm.values.sum(); mm[categoryId] = ((mm[categoryId] ?: 0f) + 1f) / (cc + 1); val total = mm.values.sum(); if (total > 0) mm.keys.forEach { mm[it] = mm[it]!! / total }; newMerchantPriors[features.merchantNormalized] = mm; return copy(categories = newCats, categoryCounts = newCounts, totalExamples = totalExamples + 1, tokenCategoryFrequencies = newTokenFreqs, categoryTokenCounts = newCatTokenCounts, vocabularySize = newVocab, merchantPriors = newMerchantPriors) }
}
